### ISSUE TITLE
CHANGES TO BE INCORPORATED IN THE WEBSITE

### ISSUE THREAD

**Issue by Sagarjit** [cleonixtechnologies/Opaque-Electronics#2]
1. FIRE SLIDE – PIONEER IN FIRE PROTECTION & DETECTION SYSTEM INSTALLATION
   AC SLIDE – CENTRALIZED AC PRODUCTS & INSTALLATION
   ELECTRICAL SLIDE – ELECTRICAL LAYOUT & INSTALLATION
   PLUMBING – PLUMBING LAYOUT
   CCTV & SECURITY SURVEILLANCE PRODUCTS
2. ALL SLIDE TRANSITIONS TO BE SMOOTH & SLIDING.
3. ADD OPAQUE LOGO TO THE WEBSITE – TOP LEFT CORNER, LOGO TEXT IN THE CENTER.
4. SERVICES DROP DOWN LIST – Installation spelling correction in HVAC drop down list.
5. Add PICTURES OF FIRE SPRINKLERS, SMOKE DETECTORS, FIRE PANEL & FIRE EXTINGUISHER IN THE TEXT SECTION OF FIRE PAGE (LOWER SECTION)
6. FIRE SECTION / HVAC SECTION & ALL OTHER SECTION – COVER PHOTO TO BE PROMINENT – NO COLOR FILTER, ADD OPAQUE LOGO IN THE TOP CORNER.
7. HVAC PAGE – ADD BLUESTAR VRF PIC IN THE SLIDE ( THE PHOTO THAT IS USED IN THE HOME PAGE – CENTER ONE)
8. CONTACT NO – 9830222718 / 9830274499 / 9830450143. Please delete the land line no.
9. EMAIL ID: - info.opaqueelectronics@gmail.com Also provide us with a website portal email 
   address.
10. CHANGE THE COVER PHOTO OF “ABOUT US “PAGE. SOME CORPORATE PICS
11. PLEASE REDUCE THE PARAGRAPH SPACING IN THE HOME PAGE. MAKE IT COMPACT.
12. ALSO ADD IN THE SECURITY COLUMN: “ WE ALSO DEAL IN (a) SOLAR PANELS (B) PUBLIC 
    ADDRESSING SYSTEM (P.A SYSTEM) (C) BOOM BARRIERS ETC.
13. Add partner logos.

**Comment by jayantapatra** [comment]
@Bubai & @i-puspita have already started working on it

**Comment by i-puspita** [comment]
designing issues are updated. Please provide the logo, clarify 
" PLEASE REDUCE THE PARAGRAPH SPACING IN THE HOME PAGE. MAKE IT COMPACT."
& inform which banner design is selected either about page or contact page?

**Comment by creating-bubai** [comment]
1. Surveilance security product
2. Fire protection
3. Index page slider and our product.
   Page are updated

**Comment by bikash02** [comment]
Thanks..
