### ISSUE TITLE
Changes in the website

### ISSUE THREAD

**Issue by Sagarjit** [cleonixtechnologies/Opaque-Electronics#3]
1. the size of the cover ph. in the home page to be reduced. Cover ph. pics to be serialized like fire, HVAC, CCTV, Electrical, & Plumbing.
2. I have send you our Co. logo & text. please include them where ever needed.
3. Cover ph. color filter transparency to be increased.
4. Contact us cover ph. to be changed
5. All provided ph no. & email ids to be included
6. All heading texts to be in bold & in designer fonts for highlighting.

please make sure that the website must be tab & mobile friendly, so that it can easily open in 3G internet speed

**Comment by i-puspita** [comment]
updated without 1& 6 point
